USE mydatabase;
SHOW TABLES;
SELECT * FROM customer_data LIMIT 20;
-- Q1 . what is the total revenue generated by male vs female customer?
SELECT gender,
       SUM(purchase_amount) AS revenue
FROM customer
GROUP BY gender;

-- Q2 . which customer used a discount but still spent more then the averege purchase amount?

SELECT customer_id,purchase_amount
FROM customer
WHERE discount_applied = 'Yes'
  AND purchase_amount >= (
        SELECT AVG(purchase_amount)
        FROM customer_data
    );
-- Q3. Which are the top 5 products with the highest average review rating?

SELECT item_purchased, 
       ROUND(AVG(CAST(review_rating AS DECIMAL(3,2))), 2) AS "Average product Rating"
FROM customer_data
GROUP BY item_purchased
ORDER BY 2 DESC
LIMIT 5;

-- Q4 compare the average purchase amounts between standard and express shipping ?
SELECT shipping_type, 
       ROUND(AVG(purchase_amount), 2) AS "Average Purchase Amount"
FROM customer_data
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;

-- Q5 Do subscribed customer spend more? compare average spend and total revenue between subscriber and non-subscribers 
select subscription_status,
COUNT(customer_id) AS total_customers,
ROUND(AVG(purchase_amount),2) as avg_spend,
ROUND(SUM(purchase_amount),2) as total_revenue
from customer
group by subscription_status
order by total_revenue,avg_spend desc; 
-- Q6 Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased,
ROUND(100*SUM(CASE WHEN discount_applied='Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;
-- Q7 Segment coustomers into new, returning,and loyal based on their total
-- number of previous purchases,and show the count of each segment?
	WITH customer_type AS (
    SELECT customer_id, previous_purchases,
    CASE
        WHEN previous_purchases = 1 THEN 'New'
        WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
        ELSE 'Loyal'
    END AS customer_segment
    FROM customer_data
)
SELECT customer_segment, COUNT(*) AS "Number of Customers"
FROM customer_type
GROUP BY customer_segment;
-- Q8. What are the top 3 most purchased products within each category?
WITH item_counts AS (
    SELECT category, item_purchased, COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM customer_data
    GROUP BY category, item_purchased
)
SELECT item_rank, category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <= 3;     
-- Q9 Are customers who are repeat buyers(more than 5 previous purchases) also likely to subscribe?
select subscription_status,
count(customer_id) as repeat_buyers
from customer
where previous_purchases >5
group by subscription_status;                                         
-- Q10 what is the revenue contribution of each age group?
SELECT age_group,
       SUM(purchase_amount) AS total_revenue
FROM customer_data
GROUP BY age_group
ORDER BY total_revenue DESC;
